version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Answerbox
  - Answerebox
  - Answererbox
  - displayminutes
  - displayseconds
  - Magicash
  - MAGICCASH
  - Mahalalel
  - minutesdisplay
  - munite
  - ndque
  - pesa
  - preprogramming
  - redirectpage
  - Sarai’s
  - secondsdisplay
  - sevensegment
  - stque
ignoreWords: []
import: []
